use crate::config::OrganizerConfig;
use std::path::Path;

/// Generate the COMMAND.md context file that Claude reads when starting
/// a session in the main/home project. This tells the orchestrator how
/// to work inside Command — how to open sessions, what projects exist, etc.
pub fn write_orchestrator_context(config: &OrganizerConfig, scripts_path: &str) {
    // Find the main project
    let main_project = config.projects.iter().find(|p| p.category == "main");
    let main_path = match main_project {
        Some(p) => &p.path,
        None => return, // No main project configured
    };

    // Build project list for context
    let mut project_lines = String::new();
    for p in &config.projects {
        if p.category == "main" {
            continue;
        }
        project_lines.push_str(&format!("  - `{}` — {} ({})\n", p.id, p.name, p.category));
    }

    let main_label = config
        .settings
        .as_ref()
        .and_then(|s| s.main_label.as_deref())
        .unwrap_or("Main");

    let context = format!(
r#"# Command App — Orchestrator Context

> This file is auto-generated by the Command app on startup.
> It provides context for the Claude orchestrator running in {main_label}.

## You Are Running Inside Command

Command is a desktop app that manages multiple concurrent Claude CLI sessions.
You are the **orchestrator** — the CTO's agent running in the {main_label} session.
Your job is to plan work, delegate to project sessions, and surface decisions to the CTO.

## How to Start Sessions in Other Projects

**CRITICAL: To open a new project tab in Command, you MUST use this exact script:**

```bash
python {scripts_path}/command-open-session.py <project-id> --prompt "your instructions here"
```

**This is NOT the same as name-session.py.** `command-open-session.py` opens a new tab in the Command app.
Command picks up the request within 2 seconds, opens the tab, and pipes your prompt.
The CTO will see the tab appear and can click into it to monitor progress.

**Do NOT try to do project work directly in Home Office. Always delegate via command-open-session.py.**

### Examples

```bash
# Start a standup review for a game
python {scripts_path}/command-open-session.py forge-and-field --prompt "Run /standup and identify the top 3 polish items"

# Kick off test fixes
python {scripts_path}/command-open-session.py necroincremental --prompt "Audit test coverage and fix failing tests"

# Start multiple projects
python {scripts_path}/command-open-session.py forge-and-field --prompt "Fix mobile viewport"
python {scripts_path}/command-open-session.py drift --prompt "Deploy latest to production"
```

## Available Projects

{project_lines}
## How We Work

1. **CTO gives direction** — "work on X, Y, Z today" or a specific task
2. **You plan the work** — break it into specs per project
3. **You delegate** — start sessions with clear prompts using command-open-session.py
4. **CTO monitors** — sees tabs light up, checks timelines, answers approvals
5. **You report** — summarize what shipped, what's blocked, what needs decisions

## Rules

- Always use command-open-session.py to open project sessions — don't try to do all the work in {main_label}
- Each session gets its own Claude instance with full project context
- Keep prompts specific and actionable — the project session should be able to run autonomously
- If a project needs CTO input, it will show as "blocked" in the sidebar
- Surface risks and decisions back to the CTO in {main_label}, don't bury them in project sessions
"#,
        main_label = main_label,
        scripts_path = scripts_path.replace('\\', "/"),
        project_lines = project_lines,
    );

    let context_path = Path::new(main_path).join("COMMAND.md");
    if let Err(e) = std::fs::write(&context_path, context) {
        eprintln!(
            "Failed to write orchestrator context to {}: {}",
            context_path.display(),
            e
        );
    } else {
        eprintln!(
            "Orchestrator context written to {}",
            context_path.display()
        );
    }
}
