use crate::config::OrganizerConfig;
use std::path::Path;

const MARKER_START: &str = "<!-- COMMAND-APP-CONTEXT-START -->";
const MARKER_END: &str = "<!-- COMMAND-APP-CONTEXT-END -->";

/// Write orchestrator context into the main project's CLAUDE.md.
/// Uses markers to replace only the Command section, preserving the rest.
pub fn write_orchestrator_context(config: &OrganizerConfig, scripts_path: &str) {
    let main_project = config.projects.iter().find(|p| p.category == "main");
    let main_path = match main_project {
        Some(p) => &p.path,
        None => return,
    };

    let claude_md_path = Path::new(main_path).join("CLAUDE.md");

    // Read existing CLAUDE.md content
    let existing = std::fs::read_to_string(&claude_md_path).unwrap_or_default();

    // Build project list
    let mut project_lines = String::new();
    for p in &config.projects {
        if p.category == "main" {
            continue;
        }
        project_lines.push_str(&format!("  - `{}` — {} ({})\n", p.id, p.name, p.category));
    }

    let main_label = config
        .settings
        .as_ref()
        .and_then(|s| s.main_label.as_deref())
        .unwrap_or("Main");

    let scripts = scripts_path.replace('\\', "/");

    let context_section = format!(
r#"{MARKER_START}
## Command App — Orchestrator Context

> Auto-generated by Command on startup. Do not edit manually — changes will be overwritten.

You are running inside the **Command** desktop app as the **orchestrator** in the {main_label} session.

### CRITICAL: How to Start Sessions in Other Projects

To delegate work to a project, you MUST use this script to open a new tab in Command:

```bash
python {scripts}/command-open-session.py <project-id> --prompt "your instructions here"
```

**This is `command-open-session.py`, NOT `name-session.py`.** They are completely different scripts.
- `command-open-session.py` = opens a new project tab in the Command app
- `name-session.py` = renames the current session (different purpose)

### Examples

```bash
python {scripts}/command-open-session.py forge-and-field --prompt "Run /standup and fix the top priority polish item"
python {scripts}/command-open-session.py necroincremental --prompt "Audit test coverage and fix failing tests"
```

### Available Project IDs

{project_lines}
### Orchestrator Rules

1. **Always delegate via command-open-session.py** — do NOT do project work directly in {main_label}
2. Each project session gets its own Claude instance with full project context
3. Keep prompts specific and actionable — the session should run autonomously
4. Surface risks and decisions back to the CTO here, don't bury them in project sessions
5. When the CTO says "work on X and Y", call command-open-session.py for each project
{MARKER_END}"#,
        MARKER_START = MARKER_START,
        MARKER_END = MARKER_END,
        main_label = main_label,
        scripts = scripts,
        project_lines = project_lines,
    );

    // Replace existing Command section or append
    let new_content = if existing.contains(MARKER_START) && existing.contains(MARKER_END) {
        let start = existing.find(MARKER_START).unwrap();
        let end = existing.find(MARKER_END).unwrap() + MARKER_END.len();
        format!("{}{}{}", &existing[..start], context_section, &existing[end..])
    } else if !existing.is_empty() {
        format!("{}\n\n{}\n", existing.trim_end(), context_section)
    } else {
        context_section
    };

    if let Err(e) = std::fs::write(&claude_md_path, new_content) {
        eprintln!("Failed to write orchestrator context to {}: {}", claude_md_path.display(), e);
    } else {
        eprintln!("Orchestrator context written to {}", claude_md_path.display());
    }

    // Clean up old COMMAND.md if it exists
    let old_command_md = Path::new(main_path).join("COMMAND.md");
    if old_command_md.exists() {
        let _ = std::fs::remove_file(&old_command_md);
    }
}
